OPENAI_API_KEY="OPENAI_API_KEY"
SF_USER='SF_USER'
SF_PASSWORD='SF_PASSWORD'
SF_ACCOUNT='SF_ACCOUNT'
SF_WAREHOUSE='SF_WAREHOUSE'
SF_DATABASE = 'SF_DATABASE'
SF_SCHEMA = 'SF_SCHEMA'
SF_ROLE='SF_ROLE'